openapi: 3.0.3
info:
  title: Text Analysis API
  version: 1.0.0
  description: API для извлечения именованных сущностей и нечеткого сопоставления.
paths:
  /back/analyze_text:
    post:
      operationId: back_analyze_text_create
      summary: Analyze input text for named entities
      tags:
      - Text Analysis
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnalyzeTextRequest'
            examples:
              ПримерТекста:
                value:
                  text: Одним солнечным днём они решили сделать что-то необычноые.
                    Вместо того, чтобы оставаться дома, Владислав и Екатерина решили
                    устроить путешествие. Они выбрали современный город. Им оказался
                    Москва.
                summary: Пример текста
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/AnalyzeTextRequest'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/AnalyzeTextRequest'
        required: true
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyzeTextResponse'
          description: Успешный запрос
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Некорректный запрос
        '422':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: 'Ошибка валидации данных '
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Ошибка сервера
components:
  schemas:
    AnalyzeTextRequest:
      type: object
      properties:
        text:
          type: string
      required:
      - text
    AnalyzeTextResponse:
      type: object
      properties:
        language:
          type: string
        entities:
          $ref: '#/components/schemas/NamedEntity'
        fuzzy_matches:
          $ref: '#/components/schemas/FuzzyMatches'
      required:
      - entities
      - fuzzy_matches
      - language
    Error:
      type: object
      properties:
        error:
          type: string
      required:
      - error
    FuzzyMatch:
      type: object
      properties:
        matched:
          type: string
        suggestion:
          type: string
        score:
          type: number
          format: double
      required:
      - matched
      - score
      - suggestion
    FuzzyMatches:
      type: object
      properties:
        persons:
          type: array
          items:
            $ref: '#/components/schemas/FuzzyMatch'
        locations:
          type: array
          items:
            $ref: '#/components/schemas/FuzzyMatch'
      required:
      - locations
      - persons
    NamedEntity:
      type: object
      properties:
        persons:
          type: array
          items:
            type: string
        locations:
          type: array
          items:
            type: string
      required:
      - locations
      - persons
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
